version: "3.8"

services:
  b3-scraper:
    build: .
    container_name: b3-scraper
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    # Para ECS, você pode adicionar:
    # cpu: 512
    # memory: 1024
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: /ecs/b3-scraper
    #     awslogs-region: us-east-1
